/* GENERATED by scripts/build-media-manifest.mjs — do not edit.
   Run `npm run media` after adding or removing files in public/work/. */

export type MediaEntry = {
  readonly poster: string;
  readonly sources: readonly { readonly src: string; readonly type: string }[];
};

export const mediaManifest: Readonly<Record<string, MediaEntry>> = {
  "community-flywheel": {
    "poster": "/work/community-flywheel.svg",
    "sources": []
  },
  "creator-partners": {
    "poster": "/work/creator-partners.svg",
    "sources": []
  },
  "lifecycle-rebuild": {
    "poster": "/work/lifecycle-rebuild.svg",
    "sources": []
  },
  "programmatic-seo": {
    "poster": "/work/programmatic-seo.svg",
    "sources": []
  },
  "video-aurora": {
    "poster": "/work/video-aurora.svg",
    "sources": []
  },
  "video-kinetic": {
    "poster": "/work/video-kinetic.svg",
    "sources": []
  },
  "video-product": {
    "poster": "/work/video-product.svg",
    "sources": []
  }
} as const;
